name: Coverage
on: push
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
          architecture: x64
      - run: pip install nox==2023.4.22
      - run: pip install poetry==1.5.1
      - run: nox --sessions tests coverage
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
